# pip install pre-commit && pip install -r requirements-dev.txt && pre-commit install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [check, ansible/]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c, .yamllint.yml]
        files: ^(local-env\.example\.yaml|ansible/controller_layout\.yml|ansible/inventory/localhost\.yml|k8s/.*\.yaml)$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^hm-playbook\.sh$

  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        language: python
        additional_dependencies:
          - ansible-core>=2.15.0
          - ansible-lint>=24.2.0
        entry: ansible-lint
        args:
          - -c
          - ansible/.ansible-lint
          - ansible/playbook.yml
          - ansible/roles
          - ansible/inventory
          - ansible/controller_layout.yml
        pass_filenames: false
