---
- name: Install base packages
  ansible.builtin.apt:
    name:
      - apache2-utils
      - ca-certificates
      - curl
      - ufw
      - wget
      - unzip
      - util-linux
      - gnupg
      - python3
      - git
    state: present
    update_cache: true
