apiVersion: apps/v1
kind: Deployment
metadata:
  name: getrafty
  namespace: hackamonth
  labels:
    app: getrafty
  annotations:
    argocd-image-updater.argoproj.io/image-list: site=hub.hackamonth.io/getrafty-org/site
    argocd-image-updater.argoproj.io/site.update-strategy: latest-version
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getrafty
  template:
    metadata:
      labels:
        app: getrafty
    spec:
      containers:
        - name: getrafty
          image: hub.hackamonth.io/getrafty-org/site:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: getrafty
  namespace: hackamonth
spec:
  selector:
    app: getrafty
  ports:
    - port: 80
      targetPort: 80
